### ISSUE TITLE
Using this template results in a "Status Crashed" using Companion 3.2.2 (3.2.2+6688-stable-7417d2a0)

### ISSUE THREAD

**Issue by lathoub** [bitfocus/companion-module-template-js#7]
Hi

I have forked this template, placed it inside of the `companion-module-dev` folder; the filled out the `manifest.json` and `package.json` until no more errors appear in the log tab.

Adding a Connection, based on the newly created module results in  **Status** Crashed cycle.

The log tab indicates: `Instance/ModuleHost: Unhandled error restarting connection: Error: Restart forced`

I was hoping for basic behaviour to build further upon. Maybe i'm doing something wrong.

I'm running Companion version [3.2.2 (3.2.2+6688-stable-7417d2a0)](https://bitfocus.io/companion/) from a fresh download from the Companion website onto a Mac M1.

[Getting started with a new module](https://github.com/bitfocus/companion-module-base?tab=readme-ov-file#getting-started-with-a-new-module) pointed me to this module template.

Or should I fork [companion-module-base](https://github.com/bitfocus/companion-module-base)?

**Comment by dg8ygz** [comment]
Seems your modules have not been "build", i fell into the same hole.
I installed  fnp and version 18 as stated in https://github.com/bitfocus/companion-module-base/wiki
then i build my package with "yarn"  in the package folder - This will install any dependencies needed by the module (noted in https://github.com/bitfocus/companion-module-base/wiki/Module-development-101 )

Then my Template startet working... maybe it helps...
cheers !
